In [3]:
#linalg
import numpy as np

In [13]:
u = np.array([1,2,3,4,5])
v = np.array([6,7,8,9,10])

u * 2

array([ 2,  4,  6,  8, 10])

In [14]:
u+v

array([ 7,  9, 11, 13, 15])

In [15]:
u*v #multiplica cada elemento

array([ 6, 14, 24, 36, 50])

In [39]:
w = np.array([1,2,3,4])
#producto punto o producto escalar (retorna un escalar)

def vector_mult(u, v):
    assert u.shape[0] == v.shape[0]
    
    result=0
    
    for i in range(u.shape[0]):
        result+=u[i]*v[i]
    return result

vector_mult(u,v)

np.int64(130)

In [25]:
A = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
B = np.array([[1,1,2],[0,0.5,1],[0,2,1],[2,1,0]])

In [33]:
#producto punto entre matriz y vector
def matrix_vector_mult(U,v):
    assert U.shape[1] == v.shape[0]
    number_rows = U.shape[0]

    result = np.zeros(number_rows)

    for i in range(number_rows):
        result[i] = vector_mult(U[i],v)

    return result

matrix_vector_mult(A, w)

array([49., 16., 15.])

In [35]:
np.dot(A,w) #multiplacion matriz vector

array([49, 16, 15])

In [36]:
#producto matriz matriz

In [43]:
def matrix_matrix_mult(U,V):
    assert U.shape[1] == V.shape[0]

    num_r = U.shape[0]
    num_c = V.shape[1]
    
    m_result = np.zeros((num_r, num_c))

    for i in range(num_c):
        vi = V[:, i] #columna i de v
        Uvi = matrix_vector_mult(U,vi) #multiplca la matriz U por la columna i de v, lo que retornaría la columna i de la matriz resultado
        m_result[:, i] = Uvi

    return m_result

matrix_matrix_mult(A,B)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [45]:
A.dot(B)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [49]:
#matriz identidad
I = np.eye(4) #tamaño matriz identidad

In [50]:
A.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [54]:
#matriz inversa solo existe en matriz cuadradas
sq = B[[0,1,2]]
sq

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])