In [1]:
import numpy as np

np

In [5]:
#Creando arrays
np.zeros(10) #Array de 10 ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
#Creando un array de un vector ya existente
a = np.array([1,2,3,4,5,10])
a

array([ 1,  2,  3,  4,  5, 10])

In [10]:
a[2] = 10
a[2] #Acceder al tercer elemento del array

np.int64(10)

In [13]:
np.arange(3, 10) #Crear un array de 3 a 9

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 11) #Crea un array del 0 al 1 con 11 elementos

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
#Arrays multidimensionales
np.zeros((5,2)) #Primer elemento es filas, segundo columnas

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
n[1][1] #Elemento del medio

np.int64(5)

In [21]:
n[1,1]

np.int64(5)

In [22]:
n[:,1] #Elementos de la segunda columna

array([2, 5, 8])

In [42]:
#Arrays generados de forma aleatoria
np.random.seed(2)
c = 100 * np.random.rand(5,2) #Cinco filas, dos columnas de 0 a 1, si queremos que sea negativo podemos usar randn
c

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [36]:
np.random.seed(2)
b = np.random.randint(low=0, high=100, size=(5,2))
b

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [37]:
b + 1

array([[41, 16],
       [73, 23],
       [44, 83],
       [76,  8],
       [35, 50]])

In [38]:
b  >= 50


array([[False, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [False, False]])

In [43]:
c >= b

array([[ True, False],
       [False,  True],
       [False, False],
       [False,  True],
       [False, False]])

In [44]:
c[c>=b] #Retorna los elementos de c que cumplen la condiciónn indicada

array([43.59949021, 43.53223926, 61.92709664])

In [49]:
c.min(),c.max(),c.sum(),c.mean(),c.std()

(np.float64(2.5926231827891333),
 np.float64(61.92709663506637),
 np.float64(358.80101767241405),
 np.float64(35.880101767241406),
 np.float64(16.34667981081927))